### PR TITLE
Reworked mutation function

### PR DESCRIPTION
**Pull request by calfcalfcalfd**
We don't have to pick a random number for each cell, we can determine the number of cell to flip, and pick random coordinates for them.

### CODE REVIEW

**Comment by terrencetec** [comment]
Thank you for your contribution. 
This somewhat changes the original mutation function. The mutation process should be a random process, instead of a definite process. The number of mutated cells in each step is different from the expected value derived from the mutation rate. Your modification however will fix the number of cells to flip, which is not the intention of the mutation function. For example, in my original code, there is a small chance that none of the cells would mutate, even the mutation rate is non-zero. However, your's says that there must be some cell that will mutate.
Undoubtedly, my implementation takes a longer time to finish compared to yours (I guess). But I think it's more fun to introduce such randomness to the game. What do you think? I think your implementation can be useful if someone desires a higher fps.

**Comment by calfcalfcalfd** [comment]
Sure, that changed the original mutation function. I hope that the new implementation will keep the randomness in the game.

**Comment by terrencetec** [comment]
I have a feeling that this is still different from the original implementation. For instance, why the would standard deviation be half of the mean? Statistically, is this the same as the original one?
Is there any particular reason why you would like to make this change?

**Comment by calfcalfcalfd** [comment]
It is not statistically the same as the original, but it is similar, with some randomness and it is more performant because it doesn't iterate on all cells, but, you are right, we don't run after the fps...

**Comment by terrencetec** [comment]
Right, did you compare the speed difference? If it's very significant then we should make an effort to include this option.

**Comment by terrencetec** [comment]
How about adding a boolean option: 
fixed_mutation: boolean
    If True, select a fixed number of cells to be mutated.

**Comment by calfcalfcalfd** [comment]
After some benchmarks, the function doesn't take a lot of time anyway. I'm closing this pull request.

**Comment by terrencetec** [comment]
Thank you very much~

**Pull request closed without merging**
